In [2]:
from rdkit import Chem
from rdkit.Chem import Descriptors
import pandas as pd
print("RDKit is working!")

RDKit is working!

In [3]:
ic50=pd.read_csv('bace1_clean.csv')

In [4]:
ic50["Mol"] = ic50["Smiles"].apply(Chem.MolFromSmiles)

ic50.head()

,Molecule ChEMBL ID,Smiles,Standard Value,Standard Units,pIC50,Mol
0,CHEMBL4216412,Cc1cc(C#N)cnc1C(=O)Nc1ccc(F)c([C@]2(C)C=C(C(F)...,63.9,nM,7.19,<rdkit.Chem.rdchem.Mol object at 0x000002FACA5...
1,CHEMBL4204742,Cc1cc(C#N)cnc1C(=O)Nc1ccc(F)c([C@]2(C)C=C(CF)O...,66.6,nM,7.18,<rdkit.Chem.rdchem.Mol object at 0x000002FACA5...
2,CHEMBL1644466,COc1ccc(C2NC(=O)c3cc(cc(N(C)S(C)(=O)=O)c3)C(=O...,3100.0,nM,5.51,<rdkit.Chem.rdchem.Mol object at 0x000002FACA5...
3,CHEMBL4062699,[2H]C1([2H])OC(N)=N[C@]12c1cc(-c3cc(Cl)cc(C#N)...,4.8,nM,8.32,<rdkit.Chem.rdchem.Mol object at 0x000002FACA5...
4,CHEMBL522778,CCCCNC(=O)[C@H](C)C[C@H](O)[C@@H]1CCCCCCCCCC(=...,7600.0,nM,5.12,<rdkit.Chem.rdchem.Mol object at 0x000002FACA5...

In [ ]:
print(ic50["Mol"].isnull().sum())

0

In [7]:
ic50["MolWt"] = ic50["Mol"].apply(Descriptors.MolWt)
ic50["LogP"] = ic50["Mol"].apply(Descriptors.MolLogP)
ic50["TPSA"] = ic50["Mol"].apply(Descriptors.TPSA)
ic50["HBD"] = ic50["Mol"].apply(Descriptors.NumHDonors)
ic50["HBA"] = ic50["Mol"].apply(Descriptors.NumHAcceptors)
ic50["RotBonds"] = ic50["Mol"].apply(Descriptors.NumRotatableBonds)

print("Descriptors calculated!")

Descriptors calculated!

In [9]:
ic50[
    [
        "Smiles",
        "MolWt",
        "LogP",
        "TPSA",
        "HBD",
        "HBA",
        "RotBonds",
        "pIC50"
    ]
].head(25)

,Smiles,MolWt,LogP,TPSA,HBD,HBA,RotBonds,pIC50
0,Cc1cc(C#N)cnc1C(=O)Nc1ccc(F)c([C@]2(C)C=C(C(F)...,415.375000,3.36220,113.39,2,6,4,7.19
1,Cc1cc(C#N)cnc1C(=O)Nc1ccc(F)c([C@]2(C)C=C(CF)O...,397.385000,3.06660,113.39,2,6,4,7.18
2,COc1ccc(C2NC(=O)c3cc(cc(N(C)S(C)(=O)=O)c3)C(=O...,722.905000,4.03440,163.37,4,8,11,5.51
3,[2H]C1([2H])OC(N)=N[C@]12c1cc(-c3cc(Cl)cc(C#N)...,423.940204,4.55038,80.63,1,5,2,8.32
4,CCCCNC(=O)[C@H](C)C[C@H](O)[C@@H]1CCCCCCCCCC(=...,425.614000,2.80380,107.53,4,4,7,5.12
5,CCCCNC(=O)[C@H](C)C[C@H](O)[C@@H]1C[C@H](C)CCC...,453.668000,3.39200,98.74,3,4,7,5.60
6,COc1nc(N2C[C@H]3C(=O)N(C)C(N)=N[C@@]3(c3c(F)cc...,420.395000,1.32932,96.94,1,7,3,7.31
7,COc1nc(N2C[C@H]3C(=O)N(C)C(N)=N[C@@]3(c3ccc(F)...,402.405000,1.19022,96.94,1,7,3,7.80
8,NC1=N[C@@](CF)(c2cc(NC(=O)c3nn(C(F)F)cc3Cl)cc(...,449.767000,3.36030,94.53,2,5,5,4.67
9,Cc1ncc(Cl)nc1C(=O)Nc1ccc(F)c([C@]2(C(F)F)N=C(N...,425.798000,3.02362,102.49,2,6,4,5.60
10,COc1cnc(C(=O)Nc2ccc(F)c([C@@]3(C(F)F)N=C(N)O[C...,440.809000,3.32880,98.83,2,6,5,7.25
11,COc1cnc(C(=O)Nc2ccc(F)c([C@@]3(C(F)F)N=C(N)O[C...,407.352000,2.07040,111.72,2,7,5,7.12
12,NC1=N[C@@](c2cc(NC(=O)c3ccc(Br)cn3)ccc2F)(C(F)...,455.234000,3.42930,89.60,2,5,4,7.61
13,CC(C)c1cc(C#N)cnc1C(=O)Nc1ccc(F)c([C@@]2(C(F)F...,443.429000,3.66188,113.39,2,6,5,6.87
14,COc1cc(C#N)cnc1C(=O)Nc1ccc(Cl)c([C@@]2(CF)N=C(...,429.839000,2.76578,122.62,2,7,5,7.09
15,[C-]#[N+]c1cnc2c(c1)CC[C@H]2Nc1ccc(F)c([C@@]2(...,413.403000,4.06469,76.89,2,5,4,6.97
16,NC1=N[C@@](c2cc(-n3cc(C#CC4CC4)cn3)ccc2F)(C(F)...,386.377000,2.96670,65.43,1,4,3,5.06
17,COc1cccnc1Nc1ccc2c(c1)C1(COC(N)=N1)C1(COC1)CO2,368.393000,1.78300,100.22,2,8,3,5.43
18,NC1=NC2(CO1)c1cc(-c3cncc(C4CC4)c3)ccc1OCC21CC1,347.418000,3.33880,69.73,1,5,2,5.43
19,CC1(C)Oc2ccc(-c3cncnc3)cc2C2(COC(N)=N2)C12COC2,352.394000,1.87140,91.85,1,7,1,6.40
20,NC1=NC2(CO1)c1cc(-c3cncc(F)c3)ccc1OC1(CCC1)C21...,381.407000,2.75960,78.96,1,6,1,5.76
21,C#Cc1cncc(-c2ccc3c(c2)C2(COC(N)=N2)C2(COC2)CO3)c1,347.374000,1.67910,78.96,1,6,1,6.29
22,Cn1ccc([C@H]2C[C@H]3CSC(N)=N[C@@]3(c3ccc(F)cc3...,364.421000,2.73290,65.43,1,5,2,6.74
23,NC1=N[C@@]2(c3ccccc3)COCC[C@H]2CS1,248.351000,1.97990,47.61,1,4,1,4.98
24,NC1=N[C@@]2(c3ccccc3F)CO[C@@H](COc3ncccn3)C[C@...,374.441000,2.35660,82.62,1,7,4,5.09

In [ ]:
ic50.to_csv("bace1_descriptors.csv", index=False)