Download PaDEL-Descriptor
PaDEL refers to calculating molecular descriptors and fingerprints for cheminformatics and machine learning using Python wrappers around the classic Java-based PaDEL-Descriptor software.

In [ ]:
%pip install PaDEL-pywrapper pandas

In [1]:
%pip install padelpy

Requirement already satisfied: padelpy in c:\Users\anuja\anaconda3\envs\qsar\Lib\site-packages (0.1.17)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
!java -version

java version "25.0.2" 2026-01-20 LTS
Java(TM) SE Runtime Environment (build 25.0.2+10-LTS-69)
Java HotSpot(TM) 64-Bit Server VM (build 25.0.2+10-LTS-69, mixed mode, sharing)

In [6]:
import padelpy
print("padelpy installed successfully!")
print(padelpy.__version__)

padelpy installed successfully!
0.1.17

In [5]:
import urllib.request
url = "https://raw.githubusercontent.com/dataprofessor/padel/main/fingerprints_xml.zip"

urllib.request.urlretrieve(url,'fingerprints_xml.zip')

print('Downloaded')

Downloaded

In [4]:
import zipfile
with zipfile.ZipFile('fingerprints_xml.zip','r') as zip_ref:
  zip_ref.extractall()

print('Extracted')

Extracted

In [3]:
import glob 

xml_files = glob.glob("*.xml")
xml_files.sort()
print(xml_files)

['AtomPairs2DFingerprintCount.xml', 'AtomPairs2DFingerprinter.xml', 'EStateFingerprinter.xml', 'ExtendedFingerprinter.xml', 'Fingerprinter.xml', 'GraphOnlyFingerprinter.xml', 'KlekotaRothFingerprintCount.xml', 'KlekotaRothFingerprinter.xml', 'MACCSFingerprinter.xml', 'PubchemFingerprinter.xml', 'SubstructureFingerprintCount.xml', 'SubstructureFingerprinter.xml']

In [2]:
from padelpy import from_smiles

fp = from_smiles(
    "CCO",
    descriptors=False,
    fingerprints=True
)

print(len(fp))

881

In [12]:
from padelpy import from_smiles

desc = from_smiles("CCO")   # Ethanol
print(type(desc))
print(len(desc))

<class 'dict'>
1875

In [7]:
df3 = pd.read_csv('BACE1_bioactivity_data_pIC50.csv')
df3

,Unnamed: 0,canonical_smiles,molecule_chembl_id,value,class,MolWt,MolLogP,NumHDonors,NumHAcceptors,pIC50
0,0,CC(C)C[C@H](NC(=O)[C@@H](NC(=O)[C@@H](N)CCC(=O...,CHEMBL406146,413.000,active,999.085,-1.43550,13,13,6.384050
1,1,CC(C)C[C@H](NC(=O)[C@H](CC(N)=O)NC(=O)[C@@H](N...,CHEMBL78946,0.002,active,893.005,-1.73610,12,12,8.698970
2,2,CCC(C)C[C@H](NC(=O)[C@H](CC(C)C)NC(C)=O)[C@@H]...,CHEMBL324109,0.460,active,751.988,2.35350,8,9,6.337242
3,5,CCC(C)C[C@H](NC(=O)[C@H](CC(C)C)NC(C)=O)[C@@H]...,CHEMBL116826,34.000,inactive,767.987,1.36900,8,9,4.468521
4,6,CC(C)[C@H](NC(=O)C[C@H](O)[C@H](Cc1cc(F)cc(F)c...,CHEMBL143239,0.020,active,717.722,4.31960,7,7,7.698970
...,...,...,...,...,...,...,...,...,...,...
7198,8809,CCOc1cc(/C=N/NC(=O)c2ccc(Cl)nc2)ccc1O,CHEMBL6173905,0.700,active,319.748,2.60320,2,5,6.154902
7199,8811,COc1cc(/C=N/NC(=O)c2ccc(Cl)nc2)ccc1O,CHEMBL6165462,0.600,active,305.721,2.21310,2,5,6.221849
7200,8812,Clc1ccc(-c2nnc(CNC3CCN(Cc4ccccc4)CC3)o2)c(Cl)c1,CHEMBL6161637,0.250,active,417.340,4.79760,1,5,6.602060
7201,8813,Nc1c2c(nc3c1C(c1cccc([N+](=O)[O-])c1)C1=C(O3)C...,CHEMBL6188525,19.600,inactive,453.454,4.30840,1,7,4.707744
7202,8814,COC(=O)c1cc(C)cc2sc3cccc(OC)c3c12,CHEMBL6190250,0.600,active,286.352,4.15812,0,4,6.221849

In [8]:
selection = ['canonical_smiles','molecule_chembl_id']
df3_selection = df3[selection]
df3_selection.to_csv('molecule.smi', sep='\t', index=False, header=False)

In [15]:
with open("molecule.smi", "r") as f:
    print(sum(1 for _ in f))

7203

In [16]:
print(len(open("molecule.smi").readlines()))

7203

In [9]:
with open('molecule.smi') as f:
  for i in range(5):
    print(f.readline().strip())

CC(C)C[C@H](NC(=O)[C@@H](NC(=O)[C@@H](N)CCC(=O)O)C(C)C)C(=O)N[C@@H](Cc1ccccc1)[C@@H](O)C(=O)N[C@@H](CC(=O)O)C(=O)N[C@@H](C)C(=O)N[C@@H](CCC(=O)O)C(=O)N[C@@H](Cc1ccccc1)C(=O)O	CHEMBL406146
CC(C)C[C@H](NC(=O)[C@H](CC(N)=O)NC(=O)[C@@H](NC(=O)[C@@H](N)CCC(=O)O)C(C)C)[C@@H](O)C[C@@H](C)C(=O)N[C@@H](C)C(=O)N[C@@H](CCC(=O)O)C(=O)N[C@@H](Cc1ccccc1)C(=O)O	CHEMBL78946
CCC(C)C[C@H](NC(=O)[C@H](CC(C)C)NC(C)=O)[C@@H](O)CC(=O)NC(CCSC)[C@@H](O)CC(=O)N[C@H](C(=O)NCc1ccc(C(=O)O)cc1)C(C)C	CHEMBL324109
CCC(C)C[C@H](NC(=O)[C@H](CC(C)C)NC(C)=O)[C@@H](O)CC(=O)NC(CC[S+](C)[O-])[C@@H](O)CC(=O)N[C@H](C(=O)NCc1ccc(C(=O)O)cc1)C(C)C	CHEMBL116826
CC(C)[C@H](NC(=O)C[C@H](O)[C@H](Cc1cc(F)cc(F)c1)NC(=O)C(O)c1ccccc1-c1ccccc1)C(=O)Nc1cc(C(=O)O)cc(C(=O)O)c1	CHEMBL143239

In [23]:
# check for invalid smiles
from rdkit import Chem

invalid = []

for i, smi in enumerate(df3['canonical_smiles']):
    if Chem.MolFromSmiles(smi) is None:
        invalid.append(i)

print("Invalid molecules:", len(invalid))
print(invalid[:20])

Invalid molecules: 0
[]

In [27]:
batch_size = 100

for i in range(0, len(df3_selection), batch_size):
    batch = df3_selection.iloc[i:i+batch_size]
    batch.to_csv(
        f"batch_{i}.smi",
        sep="\t",
        index=False,
        header=False
    )

In [ ]:
from padelpy import padeldescriptor

failed_batches = []

for i in range(0, len(df3_selection), 100):
    print(f"Running batch {i}")

    try:
        padeldescriptor(
            mol_dir=f"batch_{i}.smi",
            d_file=f"batch_{i}.csv",
            fingerprints=True,
            removesalt=True,
            threads=2
        )
    except Exception as e:
        print(f"Batch {i} failed")
        failed_batches.append(i)

print("Failed batches:", failed_batches)

In [29]:
from padelpy import padeldescriptor

failed = []

for i in range(2600, 2700):

    one = df3_selection.iloc[[i]]

    one.to_csv(
        "one.smi",
        sep="\t",
        index=False,
        header=False
    )

    try:
        padeldescriptor(
            mol_dir="one.smi",
            d_file="one.csv",
            fingerprints=True,
            removesalt=True,
            threads=1
        )

    except Exception as e:
        print(f"Failed row: {i}")
        print(df3_selection.iloc[i]["molecule_chembl_id"])
        print(e)
        failed.append(i)

print("Failed rows:", failed)

Failed row: 2662
CHEMBL506814
PaDEL-Descriptor encountered an error: Aug 05, 2026 11:34:42 PM libpadeldescriptor.CDK_Fingerprint run
SEVERE: Fingerprinter error
org.openscience.cdk.exception.CDKException: org.openscience.cdk.exception.CDKException: Timeout for AllringsFinder exceeded
	at org.openscience.cdk.smiles.smarts.SMARTSQueryTool.initializeMolecule(SMARTSQueryTool.java:363)
	at org.openscience.cdk.smiles.smarts.SMARTSQueryTool.matches(SMARTSQueryTool.java:214)
	at org.openscience.cdk.smiles.smarts.SMARTSQueryTool.matches(SMARTSQueryTool.java:189)
	at org.openscience.cdk.fingerprint.PubchemFingerprinter$CountSubstructures.countSubstructure(PubchemFingerprinter.java:312)
	at org.openscience.cdk.fingerprint.PubchemFingerprinter.countSubstructures(PubchemFingerprinter.java:1099)
	at org.openscience.cdk.fingerprint.PubchemFingerprinter._generateFp(PubchemFingerprinter.java:323)
	at org.openscience.cdk.fingerprint.PubchemFingerprinter.generateFp(PubchemFingerprinter.java:330)
	at org.openscience.cdk.fingerprint.PubchemFingerprinter.getFingerprint(PubchemFingerprinter.java:122)
	at libpadeldescriptor.CDK_Fingerprint.run(Unknown Source)
	at libpadeldescriptor.libPaDELDescriptorWorker.DoJob(Unknown Source)
	at libpadeljobs.Worker.run(Worker.java:46)
Caused by: org.openscience.cdk.exception.CDKException: Timeout for AllringsFinder exceeded
	at org.openscience.cdk.ringsearch.AllRingsFinder.checkTimeout(AllRingsFinder.java:414)
	at org.openscience.cdk.ringsearch.AllRingsFinder.remove(AllRingsFinder.java:275)
	at org.openscience.cdk.ringsearch.AllRingsFinder.doSearch(AllRingsFinder.java:202)
	at org.openscience.cdk.ringsearch.AllRingsFinder.findAllRingsInIsolatedRingSystem(AllRingsFinder.java:174)
	at org.openscience.cdk.ringsearch.AllRingsFinder.findAllRings(AllRingsFinder.java:136)
	at org.openscience.cdk.ringsearch.AllRingsFinder.findAllRings(AllRingsFinder.java:117)
	at org.openscience.cdk.smiles.smarts.SMARTSQueryTool.initializeMolecule(SMARTSQueryTool.java:360)
	... 10 more


Failed rows: [2662]

In [10]:
bad_id = "CHEMBL506814"

df3_selection = df3_selection[
    df3_selection["molecule_chembl_id"] != bad_id
]

In [11]:
df3_selection.to_csv(
    "molecule.smi",
    sep="\t",
    index=False,
    header=False
)

In [12]:
from padelpy import padeldescriptor

padeldescriptor(
  mol_dir='molecule.smi',
  d_file='Pubchem.csv',
  fingerprints=True,
  d_2d=False,
  d_3d=False,
  removesalt=True,
  standardizenitro=True,
  threads=2,
  maxruntime=600000
)


Preparing the X and Y Data Matrices

In [19]:
# X data matrix
import pandas as pd

df_X = pd.read_csv("Pubchem.csv")
print(df_X.shape)
df_X.head()

(7202, 882)

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,CHEMBL406146,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CHEMBL78946,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CHEMBL324109,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CHEMBL116826,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CHEMBL143239,1,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [20]:
df_X = df_X.drop(columns=['Name'])
df_X

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,1,1,1,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7197,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7198,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7199,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7200,1,1,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7201,1,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [18]:
# Y variable
# Convert IC50 to pIC50
df3_Y = df3['pIC50']
df3_Y

0       6.384050
1       8.698970
2       6.337242
3       4.468521
4       7.698970
          ...
7198    6.154902
7199    6.221849
7200    6.602060
7201    4.707744
7202    6.221849
Name: pIC50, Length: 7203, dtype: float64

In [21]:
# Combining X and Y variable
dataset3 = pd.concat([df_X,df3_Y], axis =1)
dataset3

,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,PubchemFP9,...,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880,pIC50
0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.384050
1,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.698970
2,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.337242
3,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.468521
4,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.698970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7198,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.154902
7199,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.221849
7200,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.602060
7201,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.707744
7202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.221849

In [23]:
dataset3.to_csv('BACE1_bioactivity data_pubchem_figerprints.csv', index = False)